In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [4]:
archivos= []
rango = range(1,31,1)
for i in rango:
    nombre = "DATOSCLIENTE" + str(i) + ".csv"
    archivos.append(nombre)

In [17]:
# Carga de datos de archivos .csv
for i in range(len(archivos)):
    url= "https://raw.githubusercontent.com/Pacheco-Carvajal/GPA-Data-ElectroDunas/main/" + archivos[i]
    temp = pd.read_csv(url)
    temp['idCliente'] = i+1
    if i==0:
        clientes = temp.copy()
    else:
        clientes = pd.concat([clientes,temp])

clientes

,Fecha,Active_energy,Reactive_energy,Voltaje_FA,Voltaje_FC,idCliente
0,2021-01-01 00:00:00,0.357841,0.282788,455.139171,510.561002,1
1,2021-01-01 01:00:00,0.372264,0.431377,469.978787,469.917178,1
2,2021-01-01 02:00:00,1.044687,0.338626,468.721120,546.949147,1
3,2021-01-01 03:00:00,0.566425,0.495791,452.329255,444.122989,1
4,2021-01-01 04:00:00,1.080556,0.472018,513.477596,535.463719,1
...,...,...,...,...,...,...
11410,2022-04-21 10:00:00,0.960105,0.473234,1273.150602,1027.084539,30
11411,2022-04-21 11:00:00,0.624300,0.699936,1063.524968,1205.829819,30
11412,2022-04-21 12:00:00,0.985633,0.123560,1207.284283,1127.893714,30
11413,2022-04-21 13:00:00,0.710436,0.399262,1205.012971,1090.835898,30
11414,2022-04-21 14:00:00,1.169279,0.013737,1145.134963,1129.472067,30

In [19]:
clientes['Fecha'] = pd.to_datetime(clientes['Fecha'])
clientes.dtypes

Fecha              datetime64[ns]
Active_energy             float64
Reactive_energy           float64
Voltaje_FA                float64
Voltaje_FC                float64
idCliente                   int64
dtype: object

In [20]:
clientes

,Fecha,Active_energy,Reactive_energy,Voltaje_FA,Voltaje_FC,idCliente
0,2021-01-01 00:00:00,0.357841,0.282788,455.139171,510.561002,1
1,2021-01-01 01:00:00,0.372264,0.431377,469.978787,469.917178,1
2,2021-01-01 02:00:00,1.044687,0.338626,468.721120,546.949147,1
3,2021-01-01 03:00:00,0.566425,0.495791,452.329255,444.122989,1
4,2021-01-01 04:00:00,1.080556,0.472018,513.477596,535.463719,1
...,...,...,...,...,...,...
11410,2022-04-21 10:00:00,0.960105,0.473234,1273.150602,1027.084539,30
11411,2022-04-21 11:00:00,0.624300,0.699936,1063.524968,1205.829819,30
11412,2022-04-21 12:00:00,0.985633,0.123560,1207.284283,1127.893714,30
11413,2022-04-21 13:00:00,0.710436,0.399262,1205.012971,1090.835898,30
11414,2022-04-21 14:00:00,1.169279,0.013737,1145.134963,1129.472067,30

In [21]:
clientes.describe()

,Active_energy,Reactive_energy,Voltaje_FA,Voltaje_FC,idCliente
count,463425.000000,463425.000000,463425.000000,463425.000000,463425.000000
mean,1.472050,0.873086,1420.188470,1438.515836,13.682710
std,1.718780,1.158846,766.299118,746.447449,8.407285
min,-1.329018,0.000000,0.031000,0.031000,1.000000
25%,0.242788,0.112832,719.462874,748.148254,6.000000
50%,0.810771,0.380650,1625.493463,1634.696089,13.000000
75%,1.992488,1.222834,2037.276385,2040.554497,20.000000
max,14.622644,11.135141,4266.229746,4399.038932,30.000000

In [22]:
clientes.groupby(by='idCliente').sum()

           Active_energy  Reactive_energy    Voltaje_FA    Voltaje_FC
idCliente
1           38196.646217     18412.379807  1.043569e+07  1.046961e+07
2           54025.520135     36774.959526  1.314844e+07  1.312308e+07
3           46087.140534     27214.308863  1.520984e+07  1.520089e+07
4           24999.616807      8371.616413  8.421717e+06  8.426430e+06
5           98383.285185     75251.385280  1.334197e+07  1.334668e+07
6           27701.401936     10399.857200  1.775682e+07  2.660811e+07
7           47749.141232      9655.812974  2.986252e+07  2.995791e+07
8           31086.482767     12323.102724  3.164910e+07  3.170344e+07
9            9761.967897     11343.700070  2.578479e+07  2.589986e+07
10          69769.980642     14449.654178  3.008088e+07  3.015663e+07
11          10693.606347       786.080888  2.705505e+07  2.685975e+07
12          12032.874814      9994.520348  1.215941e+07  1.211900e+07
13          13541.558803      2472.179155  3.024332e+07  3.021629e+07
14           2399.304947      1249.438992  2.542449e+07  2.539491e+07
15           6012.918237      4911.646934  2.892449e+07  2.889491e+07
16          25579.447721     16714.506960  3.747239e+07  3.740782e+07
17          24945.928857     20491.849921  4.011323e+07  4.004627e+07
18          27669.475796     21332.096227  4.215529e+07  4.209106e+07
19          22017.300683     16933.208620  3.543439e+07  3.537757e+07
20          21092.476706     46876.549255  4.030939e+07  4.025257e+07
21            300.562151       476.816432  1.659302e+07  1.646172e+07
22           1062.868422      1278.919312  1.762835e+07  1.765340e+07
23           1845.427423      2060.068351  1.857226e+07  1.860108e+07
24            584.901601       755.926809  1.550770e+07  1.553347e+07
25            900.978814      1082.114685  1.773895e+07  1.776472e+07
26          11696.859594      7524.836736  1.038141e+07  1.046083e+07
27          21354.625476      6958.980110  1.202774e+07  1.201116e+07
28          15278.986887      4310.055204  1.325311e+07  1.322075e+07
29           3380.499798      4208.747672  9.305663e+06  9.265252e+06
30          12032.874814      9994.520348  1.215941e+07  1.211900e+07

In [23]:
clientes.groupby(by='idCliente').mean()

           Active_energy  Reactive_energy   Voltaje_FA   Voltaje_FC
idCliente
1               1.940788         0.935541   530.241859   531.965343
2               2.745060         1.868551   668.077941   666.789056
3               2.341707         1.382771   772.818292   772.363939
4               1.270241         0.425365   427.911026   428.150518
5               4.998897         3.823555   677.911026   678.150518
6               1.407520         0.528421   902.231841  1351.969513
7               2.426154         0.490616  1517.327365  1522.174401
8               1.579517         0.626142  1608.104432  1610.865402
9               0.496010         0.576378  1310.135918  1315.982931
10              3.545042         0.734193  1528.422426  1532.271246
11              0.763829         0.056149  1932.503805  1918.553875
12              1.054128         0.875560  1065.213575  1061.673394
13              0.967254         0.176584  2160.236864  2158.306393
14              0.171379         0.089246  1816.035180  1813.922397
15              0.429494         0.350832  2066.035180  2063.922397
16              1.311767         0.857154  1921.660972  1918.349621
17              1.279278         1.050864  2057.088889  2053.654999
18              1.418947         1.093954  2161.809488  2158.515736
19              1.129092         0.868370  1817.148245  1814.234433
20              1.081665         2.403926  2067.148245  2064.234433
21              0.033676         0.053425  1859.161737  1844.450579
22              0.119089         0.143296  1975.165413  1977.971470
23              0.206771         0.230820  2080.925548  2084.154989
24              0.065535         0.084698  1737.557372  1740.444726
25              0.100950         0.121245  1987.557372  1990.444726
26              1.024692         0.659206   909.453509   916.411087
27              1.870751         0.609635  1053.678248  1052.226043
28              1.338501         0.377578  1161.026182  1158.191366
29              0.296145         0.368703   815.213575   811.673394
30              1.054128         0.875560  1065.213575  1061.673394